import type { Metadata } from "next";

import "./globals.css";
import { garamond } from '@/app/ui/fonts';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Csányi Katalin - Szobrászművész",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body
        className={`${garamond.className} antialiased bg-stone-200`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
